name: CI

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Test
        run: go test -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
